name: Continuous Deployment

on:
  push:
    branches:
      - 'main'

jobs:
  pull:
    name: Pull Stage
    runs-on: ubuntu-latest

    steps:
      - name: Sync with remote repository
        uses: appleboy/ssh-action@master
        env:
          PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PROJECT_DIR
          script_stop: true
          script: |
            cd "${PROJECT_DIR}/"
            git checkout main
            git fetch origin
            git reset --hard origin/main

  build:
    name: Build Stage
    needs: pull
    runs-on: ubuntu-latest

    steps:
      - name: Build the latest docker container
        uses: appleboy/ssh-action@master
        env:
          PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PROJECT_DIR
          script_stop: true
          script: |
            cd "${PROJECT_DIR}/"
            npm install
            npm run build

  deploy:
    name: Deploy Stage
    needs: [pull, build]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy the latest build
        uses: appleboy/ssh-action@master
        env:
          PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PROJECT_DIR
          script_stop: true
          script: |
            cd "${PROJECT_DIR}/"
            sudo rm -r /var/www/daao_ai_frontend/*
            sudo cp -r build/* /var/www/daao_ai_frontend/
            sudo nginx -s reload
